#!/usr/bin/env python3
"""Write ``docs/reference.md`` from the command registries.

The registries already hold every command's usage line and one-line summary, so
the reference is generated rather than written.  A hand-kept list of thirty
commands drifts within a month; this one cannot, and ``tests/test_reference.py``
fails if the checked-in file is out of date.

    python tools/gen_reference.py            # rewrite docs/reference.md
    python tools/gen_reference.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

import topdrawerx  # noqa: E402  (importing fills the registries)
from topdrawerx.registry import COMMANDS, SETTERS  # noqa: E402
from topdrawerx.styles import list_styles  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parents[1] / "docs" / "reference.md"

HEADER = """<!-- Generated by tools/gen_reference.py -- do not edit by hand. -->

# Command reference

topdrawerx {version}. Commands are case-insensitive and may be abbreviated to
the shortest unique prefix shown in **bold**; an ambiguous abbreviation is an
error that names the candidates.

A line of nothing but numbers is data. A line starting with `!`, `#` or `;` is a
comment, and `!` or `;` also start one part-way along a line.
"""

FOOTER = """
## Styles

`SET STYLE <name>` runs the `SET` commands in a style file. Built in:
{styles}.

Your own styles live in `~/.config/tdx/styles/` (or `$XDG_CONFIG_HOME/tdx/styles/`)
and shadow built-ins of the same name. `SAVE STYLE '<name>'` writes the current
settings there.

## Legacy compatibility

`SET DEVICE` and `SET INTENSITY` are accepted, warned about and ignored. A
command topdrawerx does not know is skipped with a note rather than aborting the
file; `--strict` turns that off, and `tdx --check <files>` reports what a pile of
old files would need.
"""


def _abbrev(name: str, minimum: int) -> str:
    """The command name with its shortest unique prefix in bold."""
    if minimum >= len(name):
        return f"**{name}**"
    return f"**{name[:minimum]}**{name[minimum:]}"


def _table(registry, prefix: str = "") -> list[str]:
    lines = ["| command | what it does |", "| --- | --- |"]
    for name in registry.names():
        cmd = registry.commands[name]
        usage = cmd.usage.replace("|", "\\|")
        summary = (cmd.summary or "").replace("|", "\\|")
        lines.append(f"| {prefix}{_abbrev(name, cmd.min_abbrev)}<br>`{usage}` | {summary} |")
    return lines


def render() -> str:
    parts = [HEADER.format(version=topdrawerx.__version__)]
    parts.append("\n## Commands\n")
    parts.extend(_table(COMMANDS))
    parts.append("\n## SET properties\n")
    parts.extend(_table(SETTERS, prefix="SET "))
    parts.append(FOOTER.format(styles=", ".join(f"`{s}`" for s in list_styles())))
    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args(argv)

    produced = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != produced:
            print("docs/reference.md is out of date: run tools/gen_reference.py", file=sys.stderr)
            return 1
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(produced, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
